### ISSUE TITLE
does not work for CC2650

### ISSUE THREAD

**Issue by hermitstars** [anasimtiaz/SwiftSensorTag#1]
could not work with the new sensor tag (cc2650stk). seems that they changed the uuid for movement sensors. are you going to work on it? thanks a lot.

**Comment by anasimtiaz** [comment]
I don't have cc2650 at the moment. I will update this once I get one. If it is simply a change in UUID then changing the corresponding variable value should be enough to make it work.

**Comment by brainray** [comment]
It should be possible to get the UUIDs from the JavaScript or Android API, they should be the same.

**Comment by hermitstars** [comment]
Thanks for reply.

I thought it was simply a change in UUID and variable value but I tried it did not work. 
I appreciate if you could update it when you get one of the new sensor. Thank you very much.

**Comment by anasimtiaz** [comment]
I will have a look when I get my hands on the device.
