### ISSUE TITLE
Doesn't work with Swift 2

### ISSUE THREAD

**Issue by ghost** [anasimtiaz/SwiftSensorTag#2]
I found this through your blog (thx!) 
however I couldn't use because it doesn't compile.

**Comment by anasimtiaz** [comment]
I haven't tried with Swift 2 but I can see why it doesn't compile. Easy fixes, I will update in few days.

**Comment by ghost** [comment]
Sounds great. Thanks!

**Comment by anasimtiaz** [comment]
Updated
