### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by ghost** [anasimtiaz/SwiftSensorTag#3]
Hello and thanks for sharing this project.
After cloning I tried to build and I get plenty of issues

/SwiftSensorTag/SwiftSensorTag/ViewController.swift
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:163:6: Unary operator cannot be separated from its operand
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:163:14: Expected expression
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:185:89: Expected ',' separator
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:199:87: Expected ',' separator
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:203:79: Expected ',' separator
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:242:88: Consecutive statements on a line must be separated by ';'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:86:10: Parameter of 'centralManagerDidUpdateState' has different optionality than expected by protocol 'CBCentralManagerDelegate'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:120:10: Parameters of 'centralManager(_:didConnectPeripheral:)' have different optionality than expected by protocol 'CBCentralManagerDelegate'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:127:10: Parameters of 'centralManager(_:didDisconnectPeripheral:error:)' have different optionality than expected by protocol 'CBCentralManagerDelegate'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:142:10: Parameters of 'peripheral(_:didDiscoverServices:)' have different optionality than expected by protocol 'CBPeripheralDelegate'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:155:10: Parameters of 'peripheral(_:didDiscoverCharacteristicsForService:error:)' have different optionality than expected by protocol 'CBPeripheralDelegate'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:179:10: Parameters of 'peripheral(_:didUpdateValueForCharacteristic:error:)' have different optionality than expected by protocol 'CBPeripheralDelegate'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:184:92: Use of unresolved identifier 'e'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:185:89: Use of unresolved identifier 'e'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:199:87: Use of unresolved identifier 'e'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:203:79: Use of unresolved identifier 'e'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:242:87: Use of undeclared type 's'
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:242:89: Expected member name or constructor call after type name
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:242:89: Add arguments after the type to construct a value of the type
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:242:89: Use '.self' to reference the type object
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:258:13: Variable 'alert' was never mutated; consider changing to 'let' constant
/SwiftSensorTag/SwiftSensorTag/ViewController.swift:100:10: Objective-C method 'centralManager:didDiscoverPeripheral:advertisementData:RSSI:' provided by method 'centralManager(_:didDiscoverPeripheral:advertisementData:RSSI:)' conflicts with optional requirement method 'centralManager(_:didDiscoverPeripheral:advertisementData:RSSI:)' in protocol 'CBCentralManagerDelegate'
/SwiftSensorTag/SwiftSensorTag/AppDelegate.swift
/SwiftSensorTag/SwiftSensorTag/AppDelegate.swift:68:51: Extra argument 'error' in call
/SwiftSensorTag/SwiftSensorTag/AppDelegate.swift:101:44: Argument passed to call that takes no arguments

**Comment by anasimtiaz** [comment]
What XCode version are you using? I tried with a different machine and can't get to replicate this.

**Comment by ghost** [comment]
Version 7.1.1 (7B1005)

**Comment by anasimtiaz** [comment]
Still can't get to reproduce this. I will wait and see if someone else points this out too.
